# Generated by Django 4.0 on 2024-07-22 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_talkmessage_sticker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkMessageEmoji',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('product_id', models.CharField(max_length=255, null=True)),
                ('emoji_id', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_message_emoji', to='talk.talkmessage')),
            ],
            options={
                'db_table': 'talk_message_emoji',
            },
        ),
    ]
