# Generated by Django 4.0 on 2024-05-04 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveStartDate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('first_date', models.DateTimeField(null=True)),
                ('second_date', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_start_date', to='reserve.reserveofflinesetting')),
                ('offline_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_start_date', to='reserve.reserveofflinecourse')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_start_date', to='reserve.reserveonlinesetting')),
                ('online_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_start_date', to='reserve.reserveonlinecourse')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_start_date', to='sign.authshop')),
            ],
            options={
                'db_table': 'reserve_start_date',
            },
        ),
    ]
