# Generated by Django 4.0 on 2024-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reservestartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveofflinesetting',
            name='advance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserveonlinesetting',
            name='advance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
