# Generated by Django 4.0 on 2024-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_reserveofflinesetting_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveofflinesetting',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserveonlinesetting',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
