# Generated by Django 4.0 on 2024-05-24 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useralert'),
        ('reserve', '0004_reserveofflinesetting_unit_reserveonlinesetting_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveUserStartDate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user_start_date', to='reserve.reserveofflinesetting')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user_start_date', to='reserve.reserveonlinesetting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user_start_date', to='user.lineuser')),
            ],
            options={
                'db_table': 'reserve_user_start_date',
            },
        ),
    ]
