# Generated by Django 4.0 on 2024-05-26 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
        ('user', '0002_useralert'),
        ('reserve', '0005_reserveuserstartdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveCalendarDate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(null=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_date', to='reserve.reserveofflinesetting')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_date', to='reserve.reserveonlinesetting')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_date', to='sign.authshop')),
            ],
            options={
                'db_table': 'reserve_calendar_date',
            },
        ),
        migrations.CreateModel(
            name='ReserveCalendarTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('time', models.TimeField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_time', to='reserve.reservecalendardate')),
            ],
            options={
                'db_table': 'reserve_calendar_time',
            },
        ),
        migrations.CreateModel(
            name='ReserveTempCalendar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_temp_calendar', to='reserve.reservecalendartime')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_temp_calendar', to='sign.authuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_temp_calendar', to='user.lineuser')),
            ],
            options={
                'db_table': 'reserve_temp_calendar',
            },
        ),
    ]
