# Generated by Django 4.0 on 2024-06-06 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
        ('reserve', '0006_reservecalendardate_reservecalendartime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveCalendarUpdate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(null=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_update', to='reserve.reserveofflinesetting')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_update', to='reserve.reserveonlinesetting')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_calendar_update', to='sign.authshop')),
            ],
            options={
                'db_table': 'reserve_calendar_update',
            },
        ),
    ]
