# Generated by Django 4.0 on 2024-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_question',
            },
        ),
        migrations.CreateModel(
            name='CompanyQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_question_item',
            },
        ),
        migrations.CreateModel(
            name='CompanyQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_question_item_choice',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_question',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_question_item',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_question_item_choice',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('use_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_question', to='question.companyquestion')),
            ],
            options={
                'db_table': 'shop_question',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_question_item', to='question.shopquestion')),
            ],
            options={
                'db_table': 'shop_question_item',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_question_item_choice', to='question.shopquestionitem')),
            ],
            options={
                'db_table': 'shop_question_item_choice',
            },
        ),
    ]
