# Generated by Django 4.0 on 2024-02-15 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0002_managerprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_question', to='sign.authcompany')),
            ],
            options={
                'db_table': 'company_question',
            },
        ),
        migrations.CreateModel(
            name='CompanyQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'name'), (2, 'kana'), (3, 'age'), (4, 'sex'), (5, 'phone'), (6, 'email'), (7, 'birth'), (8, 'address'), (9, 'profile'), (10, 'image'), (11, 'video'), (51, 'reserve_type'), (52, 'reserve_date'), (53, 'reserve_best_date'), (54, 'reserve_redate'), (99, 'question')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'text'), (2, 'radio'), (3, 'check'), (4, 'dropdown'), (5, 'date'), (6, 'time'), (7, 'date_time')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_question_item', to='question.companyquestion')),
            ],
            options={
                'db_table': 'company_question_item',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_question',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'name'), (2, 'kana'), (3, 'age'), (4, 'sex'), (5, 'phone'), (6, 'email'), (7, 'birth'), (8, 'address'), (9, 'profile'), (10, 'image'), (11, 'video'), (51, 'reserve_type'), (52, 'reserve_date'), (53, 'reserve_best_date'), (54, 'reserve_redate'), (99, 'question')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'text'), (2, 'radio'), (3, 'check'), (4, 'dropdown'), (5, 'date'), (6, 'time'), (7, 'date_time')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_question_item', to='question.headquestion')),
            ],
            options={
                'db_table': 'head_question_item',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=1, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('use_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_question', to='question.companyquestion')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_question', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_question',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'name'), (2, 'kana'), (3, 'age'), (4, 'sex'), (5, 'phone'), (6, 'email'), (7, 'birth'), (8, 'address'), (9, 'profile'), (10, 'image'), (11, 'video'), (51, 'reserve_type'), (52, 'reserve_date'), (53, 'reserve_best_date'), (54, 'reserve_redate'), (99, 'question')], default=0)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('choice_type', models.IntegerField(choices=[(1, 'text'), (2, 'radio'), (3, 'check'), (4, 'dropdown'), (5, 'date'), (6, 'time'), (7, 'date_time')], default=0)),
                ('choice_count', models.IntegerField(blank=True, null=True)),
                ('required_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_question_item', to='question.shopquestion')),
            ],
            options={
                'db_table': 'shop_question_item',
            },
        ),
        migrations.CreateModel(
            name='ShopQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_question_item_choice', to='question.shopquestionitem')),
            ],
            options={
                'db_table': 'shop_question_item_choice',
            },
        ),
        migrations.CreateModel(
            name='HeadQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_question_item_choice', to='question.headquestionitem')),
            ],
            options={
                'db_table': 'head_question_item_choice',
            },
        ),
        migrations.CreateModel(
            name='CompanyQuestionItemChoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_question_item_choice', to='question.companyquestionitem')),
            ],
            options={
                'db_table': 'company_question_item_choice',
            },
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_question', to='question.headquestion'),
        ),
    ]
