# Generated by Django 4.0 on 2024-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyquestionitem',
            name='choice_type',
            field=models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0),
        ),
        migrations.AlterField(
            model_name='companyquestionitem',
            name='type',
            field=models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0),
        ),
        migrations.AlterField(
            model_name='headquestionitem',
            name='choice_type',
            field=models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0),
        ),
        migrations.AlterField(
            model_name='headquestionitem',
            name='type',
            field=models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0),
        ),
        migrations.AlterField(
            model_name='shopquestionitem',
            name='choice_type',
            field=models.IntegerField(choices=[(1, 'フリーテキスト'), (2, 'ラジオボタン'), (3, 'チェックボックス'), (4, 'プルダウン'), (5, '日付'), (6, '時間'), (7, '日時')], default=0),
        ),
        migrations.AlterField(
            model_name='shopquestionitem',
            name='type',
            field=models.IntegerField(choices=[(1, '氏名'), (2, 'フリガナ'), (3, '年齢'), (4, '性別'), (5, '電話番号'), (6, 'メールアドレス'), (7, '生年月日'), (8, '住所'), (9, 'プロフィール写真'), (10, '画像'), (11, '動画'), (51, '予約形式'), (52, '予約日程'), (53, '予約可能日'), (54, '予約日程再調整'), (99, '設問')], default=0),
        ),
    ]
