# Generated by Django 4.0 on 2024-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopquestion',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_question', to='sign.authshop'),
        ),
        migrations.AddField(
            model_name='headquestionitemchoice',
            name='question_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_question_item_choice', to='question.headquestionitem'),
        ),
        migrations.AddField(
            model_name='headquestionitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_question_item', to='question.headquestion'),
        ),
        migrations.AddField(
            model_name='companyquestionitemchoice',
            name='question_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_question_item_choice', to='question.companyquestionitem'),
        ),
        migrations.AddField(
            model_name='companyquestionitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_question_item', to='question.companyquestion'),
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_question', to='sign.authcompany'),
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_question', to='question.headquestion'),
        ),
    ]
