# Generated by Django 4.0 on 2024-01-31 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_tag',
            },
        ),
        migrations.CreateModel(
            name='HeadTagGenre',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_tag_genre',
            },
        ),
        migrations.CreateModel(
            name='ShopTagGenre',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_tag_genre', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_tag_genre',
            },
        ),
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_tag', to='tag.shoptaggenre')),
            ],
            options={
                'db_table': 'shop_tag',
            },
        ),
        migrations.CreateModel(
            name='ShopHashTag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_hash_tag', to='sign.authshop')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_hash_tag', to='tag.companytag')),
            ],
            options={
                'db_table': 'shop_hash_tag',
            },
        ),
        migrations.CreateModel(
            name='HeadTag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_tag', to='tag.headtaggenre')),
            ],
            options={
                'db_table': 'head_tag',
            },
        ),
        migrations.CreateModel(
            name='CompanyTagGenre',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_genre', to='sign.authcompany')),
            ],
            options={
                'db_table': 'company_tag_genre',
            },
        ),
        migrations.AddField(
            model_name='companytag',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tag', to='tag.companytaggenre'),
        ),
        migrations.CreateModel(
            name='CompanyHashTag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_hash_tag', to='sign.authcompany')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_hash_tag', to='tag.headtag')),
            ],
            options={
                'db_table': 'company_hash_tag',
            },
        ),
    ]
