# Generated by Django 4.0 on 2024-04-02 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionOnlinePlace',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=1)),
                ('reception_date', models.DateTimeField(null=True)),
                ('reception_from', models.TimeField(blank=True, null=True)),
                ('reception_to', models.TimeField(blank=True, null=True)),
                ('reception_count', models.IntegerField(default=0)),
                ('reception_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_online_place', to='setting.shoponline')),
            ],
            options={
                'db_table': 'reception_online_place',
            },
        ),
        migrations.CreateModel(
            name='ReceptionOnlineManager',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=1)),
                ('reception_date', models.DateTimeField(null=True)),
                ('reception_from', models.TimeField(blank=True, null=True)),
                ('reception_to', models.TimeField(blank=True, null=True)),
                ('reception_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_online_manager', to='sign.authuser')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_online_manager', to='setting.shoponline')),
            ],
            options={
                'db_table': 'reception_online_manager',
            },
        ),
        migrations.CreateModel(
            name='ReceptionOfflinePlace',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=1)),
                ('reception_date', models.DateTimeField(null=True)),
                ('reception_from', models.TimeField(blank=True, null=True)),
                ('reception_to', models.TimeField(blank=True, null=True)),
                ('reception_count', models.IntegerField(default=0)),
                ('reception_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_offline_place', to='setting.shopoffline')),
            ],
            options={
                'db_table': 'reception_offline_place',
            },
        ),
        migrations.CreateModel(
            name='ReceptionOfflineManager',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=1)),
                ('reception_date', models.DateTimeField(null=True)),
                ('reception_from', models.TimeField(blank=True, null=True)),
                ('reception_to', models.TimeField(blank=True, null=True)),
                ('reception_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_offline_manager', to='sign.authuser')),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_offline_manager', to='setting.shopoffline')),
            ],
            options={
                'db_table': 'reception_offline_manager',
            },
        ),
        migrations.CreateModel(
            name='ReceptionData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('auto_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_data', to='sign.authshop')),
            ],
            options={
                'db_table': 'reception_data',
            },
        ),
    ]
