# Generated by Django 4.0 on 2024-05-11 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reserveofflinesetting_unit_reserveonlinesetting_unit'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionOnlineManagerSetting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_online_manager_setting', to='reception.receptiononlinemanager')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_online_manager_setting', to='reserve.reserveonlinesetting')),
            ],
            options={
                'db_table': 'reception_online_manager_setting',
            },
        ),
        migrations.CreateModel(
            name='ReceptionOfflineManagerSetting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_offline_manager_setting', to='reception.receptionofflinemanager')),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_offline_manager_setting', to='reserve.reserveofflinesetting')),
            ],
            options={
                'db_table': 'reception_offline_manager_setting',
            },
        ),
    ]
