# Generated by Django 4.0 on 2024-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import richmenu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('menu_type', models.IntegerField(choices=[(0, 'default'), (1, 'another')], default=0)),
                ('menu_flg', models.BooleanField(default=False)),
                ('menu_text', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=richmenu.models.richmenu_image_path)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='CompanyRichMenuItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=1, null=True)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'link'), (2, 'video'), (3, 'questionform'), (4, 'reserve'), (5, 'online'), (6, 'company'), (6, 'text')], default=0)),
                ('url', models.CharField(max_length=255, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_rich_menu_item',
            },
        ),
        migrations.CreateModel(
            name='HeadRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('menu_type', models.IntegerField(choices=[(0, 'default'), (1, 'another')], default=0)),
                ('menu_flg', models.BooleanField(default=False)),
                ('menu_text', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=richmenu.models.richmenu_image_path)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='HeadRichMenuItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=1, null=True)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'link'), (2, 'video'), (3, 'questionform'), (4, 'reserve'), (5, 'online'), (6, 'company'), (6, 'text')], default=0)),
                ('url', models.CharField(max_length=255, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_rich_menu_item',
            },
        ),
        migrations.CreateModel(
            name='ShopRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('menu_type', models.IntegerField(choices=[(0, 'default'), (1, 'another')], default=0)),
                ('menu_flg', models.BooleanField(default=False)),
                ('menu_text', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=richmenu.models.richmenu_image_path)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='ShopRichMenuItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=1, null=True)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'link'), (2, 'video'), (3, 'questionform'), (4, 'reserve'), (5, 'online'), (6, 'company'), (6, 'text')], default=0)),
                ('url', models.CharField(max_length=255, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu_item', to='question.shopquestion')),
                ('rich_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu_item', to='richmenu.shoprichmenu')),
            ],
            options={
                'db_table': 'shop_rich_menu_item',
            },
        ),
    ]
