# Generated by Django 4.0 on 2024-03-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0002_initial'),
        ('template', '0001_initial'),
        ('sign', '0001_initial'),
        ('richmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprichmenuitem',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu_item', to='template.shoptemplatevideo'),
        ),
        migrations.AddField(
            model_name='shoprichmenu',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu', to='sign.authcompany'),
        ),
        migrations.AddField(
            model_name='shoprichmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu', to='richmenu.companyrichmenu'),
        ),
        migrations.AddField(
            model_name='shoprichmenu',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rich_menu', to='sign.authshop'),
        ),
        migrations.AddField(
            model_name='headrichmenuitem',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_rich_menu_item', to='question.headquestion'),
        ),
        migrations.AddField(
            model_name='headrichmenuitem',
            name='rich_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_rich_menu_item', to='richmenu.headrichmenu'),
        ),
        migrations.AddField(
            model_name='headrichmenuitem',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_rich_menu_item', to='template.headtemplatevideo'),
        ),
        migrations.AddField(
            model_name='companyrichmenuitem',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rich_menu_item', to='question.companyquestion'),
        ),
        migrations.AddField(
            model_name='companyrichmenuitem',
            name='rich_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rich_menu_item', to='richmenu.companyrichmenu'),
        ),
        migrations.AddField(
            model_name='companyrichmenuitem',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rich_menu_item', to='template.companytemplatevideo'),
        ),
        migrations.AddField(
            model_name='companyrichmenu',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rich_menu', to='sign.authcompany'),
        ),
        migrations.AddField(
            model_name='companyrichmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_rich_menu', to='richmenu.headrichmenu'),
        ),
    ]
