# Generated by Django 4.0 on 2024-03-17 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sign.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('authority', models.IntegerField(choices=[(0, '一般'), (1, '閲覧者'), (2, '編集者'), (3, '管理者')], default=0)),
                ('status', models.IntegerField(choices=[(0, '停止中'), (1, '仮登録'), (2, '未認証'), (3, 'アクティブ')], default=0)),
                ('author', models.CharField(max_length=255, null=True)),
                ('head_flg', models.BooleanField(default=False)),
                ('company_flg', models.BooleanField(default=False)),
                ('delete_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', sign.models.AuthUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthCompany',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(0, '停止中'), (1, '仮登録'), (2, '未認証'), (3, 'アクティブ')], default=0)),
                ('delete_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auth_company',
            },
        ),
        migrations.CreateModel(
            name='AuthShop',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(0, '停止中'), (1, '仮登録'), (2, '未認証'), (3, 'アクティブ')], default=0)),
                ('delete_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_shop', to='sign.authcompany')),
            ],
            options={
                'db_table': 'auth_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('account_image', models.ImageField(blank=True, null=True, upload_to=sign.models.account_image_path)),
                ('head_family_name', models.CharField(max_length=255, null=True)),
                ('head_first_name', models.CharField(max_length=255, null=True)),
                ('head_family_name_kana', models.CharField(max_length=255, null=True)),
                ('head_first_name_kana', models.CharField(max_length=255, null=True)),
                ('head_phone_number', models.CharField(max_length=255, null=True)),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('head_image', models.ImageField(blank=True, null=True, upload_to=sign.models.head_image_path)),
                ('manager_family_name', models.CharField(max_length=255, null=True)),
                ('manager_first_name', models.CharField(max_length=255, null=True)),
                ('manager_family_name_kana', models.CharField(max_length=255, null=True)),
                ('manager_first_name_kana', models.CharField(max_length=255, null=True)),
                ('manager_department', models.CharField(max_length=255, null=True)),
                ('manager_phone_number', models.CharField(max_length=255, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_image', models.ImageField(blank=True, null=True, upload_to=sign.models.manager_image_path)),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('shop_postcode', models.IntegerField(blank=True, null=True)),
                ('shop_address', models.CharField(max_length=255, null=True)),
                ('shop_url', models.CharField(max_length=255, null=True)),
                ('shop_phone_number', models.CharField(max_length=255, null=True)),
                ('shop_logo_image', models.ImageField(blank=True, null=True, upload_to=sign.models.logo_image_path)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='fixture.country')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to='sign.authshop')),
                ('shop_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to='fixture.prefecture')),
            ],
            options={
                'db_table': 'shop_profile',
            },
        ),
        migrations.CreateModel(
            name='ShopNotice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('channel_id', models.CharField(max_length=255, null=True)),
                ('channel_secret', models.CharField(max_length=255, null=True)),
                ('channel_access_token', models.CharField(max_length=255, null=True)),
                ('bot_id', models.CharField(max_length=255, null=True)),
                ('follow_url', models.CharField(max_length=255, null=True)),
                ('line_flg', models.BooleanField(default=False)),
                ('mail_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_notice', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_notice',
            },
        ),
        migrations.CreateModel(
            name='ShopLine',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('channel_id', models.CharField(max_length=255, null=True)),
                ('channel_secret', models.CharField(max_length=255, null=True)),
                ('channel_access_token', models.CharField(max_length=255, null=True)),
                ('bot_id', models.CharField(max_length=255, null=True)),
                ('liff_id', models.CharField(max_length=255, null=True)),
                ('analytics_id', models.CharField(max_length=255, null=True)),
                ('qrcode_id', models.CharField(max_length=255, null=True)),
                ('reserve_id', models.CharField(max_length=255, null=True)),
                ('history_id', models.CharField(max_length=255, null=True)),
                ('follow_url', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_line', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_line',
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeToken',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_token', to='sign.authuser')),
            ],
            options={
                'db_table': 'password_change_token',
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('family_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('family_name_kana', models.CharField(max_length=255, null=True)),
                ('first_name_kana', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=sign.models.manager_profile_image_path)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=0)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('work', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='sign.authuser')),
            ],
            options={
                'db_table': 'manager_profile',
            },
        ),
        migrations.CreateModel(
            name='EmailChangeToken',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_token', to='sign.authuser')),
            ],
            options={
                'db_table': 'email_change_token',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('head_family_name', models.CharField(max_length=255, null=True)),
                ('head_first_name', models.CharField(max_length=255, null=True)),
                ('head_family_name_kana', models.CharField(max_length=255, null=True)),
                ('head_first_name_kana', models.CharField(max_length=255, null=True)),
                ('head_phone_number', models.CharField(max_length=255, null=True)),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('head_image', models.ImageField(blank=True, null=True, upload_to=sign.models.head_image_path)),
                ('manager_family_name', models.CharField(max_length=255, null=True)),
                ('manager_first_name', models.CharField(max_length=255, null=True)),
                ('manager_family_name_kana', models.CharField(max_length=255, null=True)),
                ('manager_first_name_kana', models.CharField(max_length=255, null=True)),
                ('manager_department', models.CharField(max_length=255, null=True)),
                ('manager_phone_number', models.CharField(max_length=255, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_image', models.ImageField(blank=True, null=True, upload_to=sign.models.manager_image_path)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_postcode', models.IntegerField(blank=True, null=True)),
                ('company_address', models.CharField(max_length=255, null=True)),
                ('company_url', models.CharField(max_length=255, null=True)),
                ('company_phone_number', models.CharField(max_length=255, null=True)),
                ('company_logo_image', models.ImageField(blank=True, null=True, upload_to=sign.models.logo_image_path)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='sign.authcompany')),
                ('company_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='fixture.prefecture')),
                ('company_work_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='fixture.workchild')),
                ('company_work_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='fixture.workparent')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='AuthLogin',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_login', to='sign.authcompany')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_login', to='sign.authshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_login', to='sign.authuser')),
            ],
            options={
                'db_table': 'auth_login',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='sign.authcompany'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='sign.authshop'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
