# Generated by Django 4.0 on 2024-02-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
