# Generated by Django 4.0 on 2024-03-29 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerOffline',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_offline', to='sign.authuser')),
            ],
            options={
                'db_table': 'manager_offline',
            },
        ),
        migrations.CreateModel(
            name='ManagerOnline',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_online', to='sign.authuser')),
            ],
            options={
                'db_table': 'manager_online',
            },
        ),
        migrations.CreateModel(
            name='ShopOffline',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_offline', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_offline',
            },
        ),
        migrations.CreateModel(
            name='ShopOnline',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('outline', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_online', to='sign.authshop')),
            ],
            options={
                'db_table': 'shop_online',
            },
        ),
        migrations.CreateModel(
            name='ShopOnlineTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('week', models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日'), (8, '祝')], default=0)),
                ('number', models.IntegerField(default=1)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_online_time', to='setting.shoponline')),
            ],
            options={
                'db_table': 'shop_online_time',
            },
        ),
        migrations.CreateModel(
            name='ShopOfflineTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('week', models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日'), (8, '祝')], default=0)),
                ('number', models.IntegerField(default=1)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_offline_time', to='setting.shopoffline')),
            ],
            options={
                'db_table': 'shop_offline_time',
            },
        ),
        migrations.CreateModel(
            name='ManagerOnlineTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('week', models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日'), (8, '祝')], default=0)),
                ('number', models.IntegerField(default=1)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('holiday_flg', models.BooleanField(default=False)),
                ('calendar_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_online_time', to='setting.manageronline')),
            ],
            options={
                'db_table': 'manager_online_time',
            },
        ),
        migrations.AddField(
            model_name='manageronline',
            name='online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_online', to='setting.shoponline'),
        ),
        migrations.CreateModel(
            name='ManagerOfflineTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('week', models.IntegerField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日'), (8, '祝')], default=0)),
                ('number', models.IntegerField(default=1)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('holiday_flg', models.BooleanField(default=False)),
                ('calendar_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_offline_time', to='setting.manageroffline')),
            ],
            options={
                'db_table': 'manager_offline_time',
            },
        ),
        migrations.AddField(
            model_name='manageroffline',
            name='offline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_offline', to='setting.shopoffline'),
        ),
    ]
