# Generated by Django 4.0 on 2024-05-03 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingAlert',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'info'), (2, 'notice'), (3, 'error')], default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_alert', to='sign.authshop')),
            ],
            options={
                'db_table': 'setting_alert',
            },
        ),
    ]
