# Generated by Django 4.0 on 2024-04-20 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('line_user_id', models.CharField(max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('display_image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'なし'), (1, 'フォロー'), (2, 'アンフォロー')], default=0)),
                ('member_flg', models.BooleanField(default=False)),
                ('proxy_flg', models.BooleanField(default=False)),
                ('delete_flg', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_user', to='sign.authshop')),
            ],
            options={
                'db_table': 'line_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('atelle_id', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_kana', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=0)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('background', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.user_profile_image_path)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user.lineuser')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
