# Generated by Django 4.0 on 2024-04-14 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFlow',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowAction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_action',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowActionMessage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_action_message',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowActionReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_action_reminder',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowCondition',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_condition',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowConditionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '提出'), (2, '年齢'), (3, '性別'), (4, '条件'), (5, '形式')], default=0)),
                ('text1', models.IntegerField(default=0)),
                ('text2', models.IntegerField(default=0)),
                ('radio', models.IntegerField(default=0)),
                ('check1', models.BooleanField(default=False)),
                ('check2', models.BooleanField(default=False)),
                ('check3', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_condition_item',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'template_greeting'), (2, 'template_message'), (3, 'template_video'), (4, 'template_rich_message'), (5, 'template_rich_video'), (6, 'template_card_type'), (7, 'rich_menu'), (8, 'action'), (9, 'step'), (10, 'wait'), (11, 'end'), (51, 'manual'), (52, 'timer'), (53, 'condition'), (54, 'schedule'), (55, 'result')], default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('analytics', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_item',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowResult',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_result',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowSchedule',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_schedule',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowStep',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_step',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowTab',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('member', models.IntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'any')], default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_tab',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowTemplate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_template',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowTemplateReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('repeat_flg', models.BooleanField(default=False)),
                ('repeat_date', models.IntegerField(default=0)),
                ('repeat_count_flg', models.BooleanField(default=False)),
                ('repeat_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_template_reminder',
            },
        ),
        migrations.CreateModel(
            name='CompanyFlowTimer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_flow_timer',
            },
        ),
        migrations.CreateModel(
            name='HeadFlow',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowAction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_action',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowActionMessage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_action_message',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowActionReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_action_reminder',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowCondition',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_condition',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowConditionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '提出'), (2, '年齢'), (3, '性別'), (4, '条件'), (5, '形式')], default=0)),
                ('text1', models.IntegerField(default=0)),
                ('text2', models.IntegerField(default=0)),
                ('radio', models.IntegerField(default=0)),
                ('check1', models.BooleanField(default=False)),
                ('check2', models.BooleanField(default=False)),
                ('check3', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_condition_item',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'template_greeting'), (2, 'template_message'), (3, 'template_video'), (4, 'template_rich_message'), (5, 'template_rich_video'), (6, 'template_card_type'), (7, 'rich_menu'), (8, 'action'), (9, 'step'), (10, 'wait'), (11, 'end'), (51, 'manual'), (52, 'timer'), (53, 'condition'), (54, 'schedule'), (55, 'result')], default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('analytics', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_item',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowResult',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_result',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowSchedule',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_schedule',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowStep',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_step',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowTab',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('member', models.IntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'any')], default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_tab',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowTemplate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_template',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowTemplateReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('repeat_flg', models.BooleanField(default=False)),
                ('repeat_date', models.IntegerField(default=0)),
                ('repeat_count_flg', models.BooleanField(default=False)),
                ('repeat_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_template_reminder',
            },
        ),
        migrations.CreateModel(
            name='HeadFlowTimer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'head_flow_timer',
            },
        ),
        migrations.CreateModel(
            name='ShopFlow',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('period_from', models.DateTimeField(blank=True, null=True)),
                ('period_to', models.DateTimeField(blank=True, null=True)),
                ('favorite_flg', models.BooleanField(default=False)),
                ('delete_flg', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowAction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_action',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowActionMessage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_action_message',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowActionReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_action_reminder',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowCondition',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_condition',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowConditionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, '提出'), (2, '年齢'), (3, '性別'), (4, '条件'), (5, '形式')], default=0)),
                ('text1', models.IntegerField(default=0)),
                ('text2', models.IntegerField(default=0)),
                ('radio', models.IntegerField(default=0)),
                ('check1', models.BooleanField(default=False)),
                ('check2', models.BooleanField(default=False)),
                ('check3', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_condition_item',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'template_greeting'), (2, 'template_message'), (3, 'template_video'), (4, 'template_rich_message'), (5, 'template_rich_video'), (6, 'template_card_type'), (7, 'rich_menu'), (8, 'action'), (9, 'step'), (10, 'wait'), (11, 'end'), (51, 'manual'), (52, 'timer'), (53, 'condition'), (54, 'schedule'), (55, 'result')], default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('analytics', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_item',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowResult',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_result',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowRichMenu',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_rich_menu',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowSchedule',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_schedule',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowStep',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_step',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowTab',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('member', models.IntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'any')], default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_tab',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowTemplate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_template',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowTemplateReminder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.IntegerField(default=0)),
                ('repeat_flg', models.BooleanField(default=False)),
                ('repeat_date', models.IntegerField(default=0)),
                ('repeat_count_flg', models.BooleanField(default=False)),
                ('repeat_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_template_reminder',
            },
        ),
        migrations.CreateModel(
            name='ShopFlowTimer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, '即時'), (1, '日時'), (2, '経過時間')], default=0)),
                ('date', models.IntegerField(default=0)),
                ('time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shop_flow_timer',
            },
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('end_flg', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_flow',
            },
        ),
        migrations.CreateModel(
            name='UserFlowSchedule',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_id', models.BigIntegerField()),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('time', models.TimeField(null=True)),
                ('join', models.IntegerField(choices=[(0, '未定'), (1, '参加'), (2, '不参加')], default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_flow_schedule',
            },
        ),
        migrations.CreateModel(
            name='UserFlowTimer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('action_date', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_flow_timer',
            },
        ),
    ]
