# Generated by Django 4.0 on 2024-05-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
        ('flow', '0003_userflowschedule_temp_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflowschedule',
            name='temp_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_user_flow_history', to='sign.authuser'),
        ),
    ]
