# Generated by Django 4.0 on 2024-01-24 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSort',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('sort', models.IntegerField(choices=[(0, 'なし'), (1, 'asc'), (2, 'desc')], default=0)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_sort', to='sign.authcompany')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_sort', to='sign.authuser')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_sort', to='sign.authshop')),
            ],
            options={
                'db_table': 'table_sort',
            },
        ),
        migrations.CreateModel(
            name='TableSearch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_search', to='sign.authcompany')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_search', to='sign.authuser')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_search', to='sign.authshop')),
            ],
            options={
                'db_table': 'table_search',
            },
        ),
        migrations.CreateModel(
            name='TableNumber',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_number', to='sign.authcompany')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_number', to='sign.authuser')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_number', to='sign.authshop')),
            ],
            options={
                'db_table': 'table_number',
            },
        ),
    ]
